#!/bin/sh
a=`git status -s` 

array=(${a//,/ })  
for var in ${array[@]}
do
    if [ "$var" = "M" ] || [ "$var" = "A" ]; then
        continue
    fi
    # phplint
#    phplintResult=`/usr/local/var/www/githooks/vendor/bin/phplint $var | grep error`
    phplintResult=`./vendor/bin/phplint $var | grep error`
    if [ x"$phplintResult" != x ]; then 
        echo "-------------------------------------"
        echo "Git commit error, get phplint errors:"
        /usr/local/var/www/githooks/vendor/bin/phplint $var | while read line
        do 
            echo $line
        done
        echo "-------------------------------------"
        exit 1
    fi

    # phpcs
    phpcsResult=`phpcs --standard=psr2 $var | grep ERROR`
    if [ x"$phpcsResult" != x ]; then 
        echo "-------------------------------------"
        echo "Git commit error, get phpcs errors:"
        phpcs $var | while read line 
        do 
            echo $line
        done
        echo "-------------------------------------"
    fi
done
exit 0
