#!/bin/sh

# read config file
source ./phpcc.ini

# check if phplint_path is config
if [ x"$phplint_path" = x ]; then
    phplint_path="./vendor/bin/phplint"
fi

# check if phpcs_path is config
if [ x"$phpcs_path" = x ]; then
    phpcs_path="phpcs"
fi

a=`git status -s` 

array=(${a//,/ })  
for var in ${array[@]}
do
    if [ "$var" = "M" ] || [ "$var" = "A" ] || [ "$var" = "D" ]; then
        continue
    fi

    # check php file
    if [[ ! $var =~ ".php" ]]; then
        echo "Check file $var: not php file, ignoring..."
        continue
    fi

    # phplint
    if [[ $phplint == "true" ]]; then
        phplintResult=`./vendor/bin/phplint $var | grep error`
        if [ x"$phplintResult" != x ]; then
            echo "-------------------------------------"
            echo "Git commit error, get phplint errors:"
            ./vendor/bin/phplint $var | while read line
            do
                echo $line
            done
            echo "-------------------------------------"
            exit 1
        else
            echo "phplint file [$var] success !"
        fi
    fi

    # phpcs
    if [[ $phpcs == "true" ]]; then
        phpcsResult=`phpcs --standard=psr2 $var | grep ERRORS | grep -v "0 ERRORS"`
        if [ x"$phpcsResult" != x ]; then
            echo "-------------------------------------"
            echo "Git commit error, get phpcs errors:"
            phpcs $var | while read line
            do
                echo $line
            done
            echo "-------------------------------------"
            exit 1
        else
            echo "phpcs file [$var] success !"
        fi
    fi
done

echo "Congratulations! Code check success!"
exit 0
